### ISSUE TITLE
Hero (multiple variations)

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#10]
**Variation 1: Hero with background video and form**

![hero-video](https://user-images.githubusercontent.com/7074782/220497747-3d6181f3-6b18-4dda-ad98-dd5b661e0ca6.png)

**Variation 2: Hero with background video and no form**

![hero-video-alternate-no-form](https://user-images.githubusercontent.com/7074782/220497806-2e46c0f3-9859-4117-b716-45df8ed51951.png)

**Variation 3: Hero with background image and CTA button**

![hero-image](https://user-images.githubusercontent.com/7074782/220497879-ce8a2f09-9f7a-42f9-90fc-0c3e1873645f.png)
![hero-image-button-alternate](https://user-images.githubusercontent.com/7074782/220497883-ecdd8ef3-6932-45a9-b037-ee3f4a12b921.png)
≈

**Comment by tmathern** [comment]
As seen in:
- Variation 1: https://www.caesars.com/caesars-palace/hotel
- Variation 2: https://www.caesars.com/caesars-palace/things-to-do/nightlife
- Variation 3: https://www.caesars.com/caesars-palace/casino/race-and-sports-book

**Comment by tmathern** [comment]
There is another variation:
- Variation 4: Hero with background-image carousel, as seen in https://www.caesars.com/caesars-palace/shows

**Comment by tmathern** [comment]
@amol-anand Wdyt? Actually I was thinking on doing Variation 2, 3 and 4.
We'd need a form block too (but as another issue?).

**Comment by amol-anand** [comment]
Yes, the homepage also has a carousel + different form in hero. which is your 4th variation. Form blocks would be a separate issue.

**Comment by tmathern** [comment]
I created https://github.com/hlxsites/caesars/issues/48 for the form blocks.

**Comment by tmathern** [comment]
https://github.com/hlxsites/caesars/issues/48

**Comment by tmathern** [comment]
https://github.com/hlxsites/caesars/issues/11

**Comment by tmathern** [comment]
https://github.com/hlxsites/caesars/issues/52 (Image carousel)
