### ISSUE TITLE
Card Slider (multiple variations)

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#11]
**Variation 1: Carousel with cards**

![carousel-option1-deals](https://user-images.githubusercontent.com/7074782/220498088-2aa37c14-39e9-4ca9-be0c-7a512342e510.png)

**Variation 2: Carousel with large cards (Rooms)**
![carousel-option2-rooms](https://user-images.githubusercontent.com/7074782/220498166-c0ec8d27-5761-4913-9981-6cd704d75f83.png)

**Variation 3: Carousel with cards**
![carousel-option-3](https://user-images.githubusercontent.com/7074782/220498217-cb5d0cee-bc8d-4f29-a66e-313f8cdfdf4d.png)

**Comment by tmathern** [comment]
Image carousel "initial" carousel: https://github.com/hlxsites/caesars/issues/52

**Comment by tmathern** [comment]
As discussed with @amol-anand, skipping version 2 for this issue. So only variations 1 and 3 have to be done for the carousel.
