### ISSUE TITLE
Card List (with and without Filters)

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#12]
**Variation 1: Card List with Filters**

![cards-filter-restaurants](https://user-images.githubusercontent.com/7074782/220499009-6da25e56-4112-4d6b-8152-e8d981e92823.png)
![cards-filter-shows](https://user-images.githubusercontent.com/7074782/220499010-91908e54-dca2-455a-8bbe-a0d958674c08.png)

**Variation 2: Card List without Filters**

![cards-nofilter](https://user-images.githubusercontent.com/7074782/220499172-524c7c58-4647-4ec3-9593-34c659ea59d0.png)

**Dev notes:** Use a specialized index for the type of page (Shows/Restaurants/etc..) and then pull that index json in automatically based on whatever is published and the block can then build the Card per item.

**Comment by amol-anand** [comment]
Special "Open Now" checkbox needs to look at local browser time and compare with restaurant opening hours that should be coming from the meta tags of the target restaurant page

**Comment by amol-anand** [comment]
@chrismborland go for it.

**Comment by chrismborland** [comment]
Removed variation (3) and created `card-slider` block issue - #38

**Comment by tmathern** [comment]
Note that I think that in phase 2, instead of tabs on mobile we should use the card slider.
