### ISSUE TITLE
Columns (Variations)

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#13]
**Variation 1: Columns with Image, text, cta**

![columns-3-alternate](https://user-images.githubusercontent.com/7074782/220499589-b3bea22c-361d-40a8-85ff-9ab16e3fd4d8.png)

**Variation 2: equal width columns**

![content-image-columns](https://user-images.githubusercontent.com/7074782/220500102-47f00ca0-b3da-4a65-adec-4e2868c34c3b.png)

**Variation 3: unequal width columns**

![columns-alternate1](https://user-images.githubusercontent.com/7074782/220499696-e19b4a7f-1b93-420d-84b6-1f1073ad132d.png)
![columns-alternate1-mirror](https://user-images.githubusercontent.com/7074782/220499697-fa05ec07-2fd5-40ac-bce3-2f9cdea61351.png)

**Comment by arumsey** [comment]
@amol-anand Is the preferred approach when seeing all these variations on the column pattern to just enhance the existing column block to support the variations vs. creating a new block for each variation?

What have you found authors prefer? Always creating `columns` blocks and then applying variations via additional style names and/or meta data? Or, creating different blocks for each variation?
