### ISSUE TITLE
Product Details - Menus and Dining options

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#139]
![menus-dining-options](https://user-images.githubusercontent.com/7074782/229331160-c4da681b-5f35-43c2-9d43-fa1be87e6223.png)

Notes: This should be built as a separate block that will get called from Product Details. 
Individual menus will point to separate pages
Hours is an overlay
All data / content needed will come from the Excel. If it is not there already, we will add it in.

**Comment by amol-anand** [comment]
@swetabar I'll probably take this one on since I'm already in the thick of product details stuff if that is ok with you.

**Comment by swetabar** [comment]
Hi @amol-anand - I've already started work on it. I'm planning to send a PR soon.
