### ISSUE TITLE
CTA

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#14]
![content-image-cta-alternate](https://user-images.githubusercontent.com/7074782/220500242-9bb9a3a9-6acb-4dbd-a03f-e3e1f5df5754.png)

**Comment by tmathern** [comment]
I see multiple part in this block - Image, texts (title + description) and a button ("Learn more...").

<img width="960" alt="Screenshot 2023-02-22 at 1 33 22 PM" src="https://user-images.githubusercontent.com/60901087/220770631-e6315020-5486-4aec-85fc-de9c63c7b3e0.png">

<img width="960" alt="Screenshot 2023-02-22 at 1 33 35 PM" src="https://user-images.githubusercontent.com/60901087/220770660-4e144c7b-5c37-4c58-b86e-02b8d260489f.png">

Regarding the button, it will stay and have possibly variable text, correct?

**Comment by tmathern** [comment]
As seen in https://www.caesars.com/caesars-palace/hotel
