### ISSUE TITLE
Product Details - Description, tags and hours

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#140]
![Product Description tags and hours](https://user-images.githubusercontent.com/7074782/229331228-c72839e7-4820-4945-ad85-4fcd466a17ad.png)

Notes: This block should be built separately and it will be included in the Product Details page like the other blocks are included. Content will be provided from the JSON to build this block but for development assume that someone is authoring this. We will dynamically get the right content from the JSON and send it to the block to be built. 

Now Open uses user browser's local time to see if it is within the start and end times of the opening of this place. 

Also look at variations under show details pages

**Comment by tmathern** [comment]
Shows variants:
<img width="1494" alt="Screenshot 2023-04-03 at 10 32 26 AM" src="https://user-images.githubusercontent.com/60901087/229584348-fa44bcd7-8de7-4857-aaa1-f7cc689647e6.png">

<img width="1494" alt="Screenshot 2023-04-03 at 10 33 13 AM" src="https://user-images.githubusercontent.com/60901087/229584501-66762115-ae47-4f92-beaf-e9451404bbf0.png">

**Comment by tmathern** [comment]
Nightlife variants:
<img width="1494" alt="Screenshot 2023-04-03 at 10 35 15 AM" src="https://user-images.githubusercontent.com/60901087/229585035-173958d4-a160-499e-86bc-7c7325e14031.png">

<img width="1494" alt="Screenshot 2023-04-03 at 10 35 59 AM" src="https://user-images.githubusercontent.com/60901087/229585055-3fce59aa-7da7-4cc2-9352-3735847fe102.png">

**Comment by tmathern** [comment]
Variants:
- "Standard" with logo, description, "OPEN NOW" box, and a line of icons+text;
- line of icons+text only;

Configuration options: Add "Open now" boxing using opening hours config line.

**Comment by amol-anand** [comment]
Open now should be automatic (author should not have to do anything for that) based on the timings. If timings are entered, then it will show up, otherwise it will not.

**Comment by tmathern** [comment]
That is what I meant, @amol-anand. We need a way to know/detect the timings. SHould it be a block configuration or something else?

**Comment by tmathern** [comment]
Opening hours overlay:
<img width="357" alt="Screenshot 2023-04-03 at 10 53 01 AM" src="https://user-images.githubusercontent.com/60901087/229588495-42d763ee-475b-48d6-b067-e510b620cc92.png">
