### ISSUE TITLE
Hero title

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#141]
Do we have a way to keep the title to the right or left by any chance?

![Screenshot 2023-04-02 at 12 44 08 AM](https://user-images.githubusercontent.com/7074782/229331794-caad4e4d-6e8d-4cdd-bbd5-8310179a6142.png)

Source:
https://www.caesars.com/caesars-palace/restaurants/hells-kitchen

**Comment by tmathern** [comment]
Not yet, @amol-anand. We'd need to add variants.
