### ISSUE TITLE
Review Sportsbook Page

### ISSUE THREAD

**Issue by jfait** [hlxsites/caesars#152]
https://www.caesars.com/caesars-palace/casino/race-and-sports-book
https://main--caesars--hlxsites.hlx.page/caesars-palace/casino/race-and-sports-book

**Comment by jfait** [comment]
![image](https://user-images.githubusercontent.com/1164937/230409048-e8645392-49ab-4909-8d84-b753477fc713.png)

1. Hero font size is smaller (but looks like its authored like other pages ?)
2. Hero footer is missing (i don't see a variation like this in authoring guide, atm. or maybe its not meant to be a variation and it can be authored

**Comment by jfait** [comment]
> ![image](https://user-images.githubusercontent.com/1164937/230409048-e8645392-49ab-4909-8d84-b753477fc713.png)

@amol-anand @tmathern should this be a hero variation or should i try to author as section with columns etc?

**Comment by jfait** [comment]
![image](https://user-images.githubusercontent.com/1164937/230413511-d585b817-0795-4bcb-9ad8-5ca6befdab11.png)

Button authoring issue logged separately as #151

**Comment by amol-anand** [comment]
1. just added the text we want in each line and that seems to have fixed this. take a look at the word doc
2. Both were just built in the last 2 days. one i being reviewed so should be in by tomorrow / day after at the latest.
3. yes, there is a little css thing that is on top of the hero image. I'll take a look at that one.
