### ISSUE TITLE
Review Shows Page

### ISSUE THREAD

**Issue by jfait** [hlxsites/caesars#153]
https://www.caesars.com/caesars-palace/shows
https://main--caesars--hlxsites.hlx.page/caesars-palace/shows

**Comment by jfait** [comment]
FEATURE-CARD
![image](https://user-images.githubusercontent.com/1164937/230421927-4496e871-34bc-445c-84f7-ad257019528b.png)

1. all caps
2. font
3. sizing

**Comment by swetabar** [comment]
> CAROUSEL
> 
> ![image](https://user-images.githubusercontent.com/1164937/230418922-5a0d03ad-8ca6-49a2-8154-a9609b397fd3.png)
> 
> 1. Individual cards can have different text alignments
> 2. spacing gap between button and text (I've removed the white space in authored page with no impact so not something author did or can fix

@jfait / @amol-anand - Looks like Caesar's modified this page to include a hero block. I don't see a carousel anymore here: https://www.caesars.com/caesars-palace/shows. I'll modify the authoring content to include a hero block instead of a carousel.
