### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#16]
![tabs](https://user-images.githubusercontent.com/7074782/220500405-834c4ef7-7c6f-4760-b57a-418370d5ad1b.png)

**Comment by arumsey** [comment]
https://www.caesars.com/caesars-palace/things-to-do/weddings

**Comment by tmathern** [comment]
There are 3 kinds of tabs:
<img width="1116" alt="Screenshot 2023-02-27 at 12 42 31 PM" src="https://user-images.githubusercontent.com/60901087/221681145-f8bbb56b-c5ce-48a1-9437-1c6b1bf1513b.png">
<img width="1116" alt="Screenshot 2023-02-27 at 12 42 41 PM" src="https://user-images.githubusercontent.com/60901087/221681157-b4199c4f-25ba-499d-b105-c582facb0216.png">
<img width="1153" alt="Screenshot 2023-02-27 at 12 42 58 PM" src="https://user-images.githubusercontent.com/60901087/221681178-c695e6a5-e44a-4107-8777-3969d256d720.png">

**Comment by arumsey** [comment]
Could we treat each tab as a row in a table where each row has two columns?

Column 1 = optional image
Column 2 = tab content

A bold link will automatically get styled as a primary button when added as content.

Is all of this content authored or is it meant to come from data in a spreadsheet?

**Comment by tmathern** [comment]
@arumsey Spreadhseet meaning eg. Excel? Or did you mean an array in a Word doc?
I've asked about how the content is created - authored of from a data spreadhseet.

**Comment by tmathern** [comment]
Note: Menus will be handled as a separate component.
