### ISSUE TITLE
Truncating of text is too aggressive

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#169]
Even single lines are truncated when it should not.

https://issue-136-casino-page--caesars--hlxsites.hlx.page/caesars-palace/drafts/swbarman/casino 
![Screenshot 2023-04-17 at 11 44 13 AM](https://user-images.githubusercontent.com/7074782/232539503-8dd53451-016e-48f7-ba7e-f83f8926fbf3.png)

**Comment by tmathern** [comment]
@arumsey In the future we'll have to either find another way for the config, or make it more robust. It's hard to get the hang of that config thing...
