### ISSUE TITLE
Block:  Intro Section

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#17]
![text-image-bg-fullwidth](https://user-images.githubusercontent.com/7074782/220500483-1a99a46d-5cd3-43ab-ba1c-ff5f14142526.png)

<img width="994" alt="Screenshot 2023-02-23 at 12 56 12 PM" src="https://user-images.githubusercontent.com/3279046/220991103-16c3bbcf-1199-4c21-b2e1-05ebcf23316a.png">

<img width="491" alt="Screenshot 2023-02-23 at 12 56 23 PM" src="https://user-images.githubusercontent.com/3279046/220991122-0d707e46-f88c-47a5-8746-0580954a7f71.png">

**Comment by amol-anand** [comment]
Includes a background image for the section

**Comment by chrismborland** [comment]
Background can now be added as a section background and has been excluded from this block specifically.

**Comment by chrismborland** [comment]
<img width="698" alt="authoring-experience" src="https://user-images.githubusercontent.com/3279046/221297303-6c077179-a80c-4c28-b53f-60cdb9858944.png">
