### ISSUE TITLE
Slider: Fix mobile + tablet view for sliders

### ISSUE THREAD

**Issue by swetabar** [hlxsites/caesars#178]
![Screen Shot 2023-04-18 at 4 29 56 PM](https://user-images.githubusercontent.com/15715290/232897740-5f4eff02-7bf7-45e0-9c8e-05a181ff1770.png)
![Screen Shot 2023-04-18 at 4 30 10 PM](https://user-images.githubusercontent.com/15715290/232897794-9024d864-55dc-4e5b-9901-8cb1c08b4b66.png)
![Screen Shot 2023-04-18 at 4 30 26 PM](https://user-images.githubusercontent.com/15715290/232897846-d7f87f26-c737-4f39-8048-a651f4ddb236.png)
![Screen Shot 2023-04-18 at 4 30 39 PM](https://user-images.githubusercontent.com/15715290/232897883-0c9b55ed-681b-4f92-aefa-b3d0c62ff986.png)

![Screen Shot 2023-04-19 at 3 43 16 PM](https://user-images.githubusercontent.com/15715290/233183000-2625c8a2-79b9-4937-82cc-5ed577747c06.png)

Fix spacing and other text issues related to sliders.

**Comment by tmathern** [comment]
There is also an issue with button placement on mobile, probably some CSS to fix on the responsive breakpoints: 
<img width="585" alt="Screenshot 2023-04-19 at 1 21 45 PM" src="https://user-images.githubusercontent.com/60901087/233191109-9d0dcf06-1457-4f4e-9256-47f1889d48e4.png">

**Comment by tmathern** [comment]
When there are only two itens in the sliders, the available space should split evenly in two:
<img width="1604" alt="Screenshot 2023-04-20 at 3 18 39 PM" src="https://user-images.githubusercontent.com/60901087/233499170-0c52ec4b-2ac1-41e3-85a0-70fcc343f207.png">

**Comment by tmathern** [comment]
The slider cards also should support having two buttons, like this:
<img width="1604" alt="Screenshot 2023-04-20 at 4 14 38 PM" src="https://user-images.githubusercontent.com/60901087/233505960-379e936b-ceea-44a0-87d0-6b0b6d680ae1.png">

(See https://www.caesars.com/caesars-palace/things-to-do/football#0)

**Comment by swetabar** [comment]
> The slider cards also should support having two buttons, like this: <img alt="Screenshot 2023-04-20 at 4 14 38 PM" width="1604" src="https://user-images.githubusercontent.com/60901087/233505960-379e936b-ceea-44a0-87d0-6b0b6d680ae1.png">
> 
> (See https://www.caesars.com/caesars-palace/things-to-do/football#0)

Looks like this one is not a slider. It's a plain grid of cards. Should we create a separate issue / block for it?
@tmathern @amol-anand
