### ISSUE TITLE
Section Variations

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#18]
**Variation 1: Background image and one column of content**

![section-bg-image-1col-content](https://user-images.githubusercontent.com/7074782/220500656-3becf10f-639b-4156-b285-4fdc956c4994.png)
![section-bg-image-1col-content-alternate](https://user-images.githubusercontent.com/7074782/220500660-7debde60-3a3e-4cf6-8c07-9b8d7d1d3c50.png)

**Variation 2: Section with Background image but can have any content in it**
![section-bg-image](https://user-images.githubusercontent.com/7074782/220500753-345dfd14-daec-40ee-a12a-56e6979eaa83.png)

**Variation 3: Section with Background image with column content but includes centered icons at the bottom**
![section-bg-color-with-icons](https://user-images.githubusercontent.com/7074782/220500840-377c7985-1905-4e2d-ada2-8ff18ef6bd7b.png)

**Comment by arumsey** [comment]
Fixed by #25 

Section meta data can include `has-background` and `has-overlay` styles. Background image will be picked from first image found in the section.
