### ISSUE TITLE
Add ability to control where text overlay goes on product pages

### ISSUE THREAD

**Issue by tmathern** [hlxsites/caesars#184]
Currently, the text overlay on the images' behavior is hard coded.
We need to be able to control if it goes left or right, as not all product pages follow the same logic (it's not always zig-zag). 
I think we already have a column we could use for this in Excel, the `Style` column.
Example: See https://www.caesars.com/caesars-palace/shows/absinthe

**Comment by amol-anand** [comment]
Checking with Spencer first. I don't think we should complicate the authoring experience. They should just enter the content and not worry about whether the text will be left or right and it is up to the consuming app to decide that look and feel.

**Comment by amol-anand** [comment]
Checked with spencer. We want the authors to decide whether the text overlay would be on the left or right from the excel.
