### ISSUE TITLE
Product Pages: Fix Attire SVGs

### ISSUE THREAD

**Issue by swetabar** [hlxsites/caesars#191]
E.g., https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/structured-content/restaurants/cafe-americano
![Screen Shot 2023-04-20 at 3 32 58 PM](https://user-images.githubusercontent.com/15715290/233469482-a3a563ad-3e61-46b4-8306-beb00846224b.png)

Casual should have a t-shirt icon as seen in: https://www.caesars.com/caesars-palace/restaurants/cafe-americano

Similar issue seen for Formal & Business Casual attires.

Also, cuisine : `American` should be a burger instead of a fork and a knife.

**Comment by amol-anand** [comment]
I'm going to update the code to use the same text converted to lower-kebab-case as the icon name. As long as we have the icons in the code, we should then be all set.

**Comment by amol-anand** [comment]
@swetabar I've updated the code for cuisine to also be the same as attire. You need to find the missing icons and upload them with the right name of the svg as generated by the code (lower-kebab-case of the actual value from excel). Then it will work automatically
