### ISSUE TITLE
Product Pages: Fix the implementation of menu options block

### ISSUE THREAD

**Issue by swetabar** [hlxsites/caesars#192]
Currently there are multiple restaurants which have different columns in the menu options block.
They can have 2, 3, 4, or 5 columns.
Figure out a way to handle all the edge cases.
![Screen Shot 2023-04-20 at 3 58 43 PM](https://user-images.githubusercontent.com/15715290/233474619-14a45f27-eaac-4df1-8419-2b90eee92c25.png)
![Screen Shot 2023-04-20 at 3 59 21 PM](https://user-images.githubusercontent.com/15715290/233474809-210b6fb7-d27f-4ba9-a6b5-727a8476a789.png)

**Comment by amol-anand** [comment]
also this error in the browser console 

`failed to load module for menu-options DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at http://localhost:3000/caesars-palace/blocks/menu-options/menu-options.js:15:17
    at NodeList.forEach (<anonymous>)
    at http://localhost:3000/caesars-palace/blocks/menu-options/menu-options.js:14:14
    at Array.forEach (<anonymous>)
    at Module.decorate (http://localhost:3000/caesars-palace/blocks/menu-options/menu-options.js:10:6)
    at http://localhost:3000/caesars-palace/scripts/lib-franklin.js:360:32`
