### ISSUE TITLE
Product Pages: Fix restaurant timing for days when it is closed

### ISSUE THREAD

**Issue by swetabar** [hlxsites/caesars#194]
https://www.caesars.com/caesars-palace/restaurants/mr-chow

![Screen Shot 2023-04-20 at 4 06 48 PM](https://user-images.githubusercontent.com/15715290/233476261-b92280cf-efbd-4bd4-a9b4-f5bab0e37399.png)

**Comment by amol-anand** [comment]
@swetabar  Also need an image for this restaurant and the video url should be from the existing DAM (not in sharepoint). please fix the hero image and video. I've added a new columns called Hero Video for this purpose.

**Comment by tmathern** [comment]
@amol-anand I think this may be related to Excel. I checked, and "Closed" is supported in the component/block used for the hours. So we need to find a way to convey that notion in Excel, and so that it still validates. Maybe leaving the line empty should mean closed?

**Comment by amol-anand** [comment]
I can take that part on. Keep it as "Closed" for now in the excel.
