### ISSUE TITLE
Link styling in FAQ is off

### ISSUE THREAD

**Issue by tmathern** [hlxsites/caesars#198]
Link styling in FAQ should look like inline clickable text.

Currently instead it looks like this:
<img width="1604" alt="Screenshot 2023-04-20 at 3 53 19 PM" src="https://user-images.githubusercontent.com/60901087/233503553-70e1c0c6-44b8-49a3-846a-9f5e1ba697ac.png">

**Comment by amol-anand** [comment]
might be related to #159 ?

**Comment by tmathern** [comment]
Maybe. It will need fixing anyway.
