### ISSUE TITLE
Things to Do Content

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#35]
[/caesars-palace/things-to-do](https://www.caesars.com/caesars-palace/things-to-do)
[/caesars-palace/things-to-do/garden-of-the-gods-pool-oasis](https://www.caesars.com/caesars-palace/things-to-do/garden-of-the-gods-pool-oasis)
[/caesars-palace/things-to-do/golf](https://www.caesars.com/caesars-palace/things-to-do/golf)
[/caesars-palace/things-to-do/nightlife](https://www.caesars.com/caesars-palace/things-to-do/nightlife)
[/caesars-palace/things-to-do/nightlife/alto-bar](https://www.caesars.com/caesars-palace/things-to-do/nightlife/alto-bar)
[/caesars-palace/things-to-do/nightlife/vista-cocktail-lounge](https://www.caesars.com/caesars-palace/things-to-do/nightlife/vista-cocktail-lounge)
[/caesars-palace/things-to-do/nightlife/montecristo-cigar-bar](https://www.caesars.com/caesars-palace/things-to-do/nightlife/montecristo-cigar-bar)
[/caesars-palace/things-to-do/nightlife/lobby-bar](https://www.caesars.com/caesars-palace/things-to-do/nightlife/lobby-bar)
[/caesars-palace/things-to-do/nightlife/numb-bar-and-frozen-cocktails](https://www.caesars.com/caesars-palace/things-to-do/nightlife/numb-bar-and-frozen-cocktails)
[/caesars-palace/things-to-do/nightlife/stadia](https://www.caesars.com/caesars-palace/things-to-do/nightlife/stadia)
[/caesars-palace/things-to-do/nightlife/purple-zebra](https://www.caesars.com/caesars-palace/things-to-do/nightlife/purple-zebra)
[/caesars-palace/things-to-do/nightlife/galleria-bar](https://www.caesars.com/caesars-palace/things-to-do/nightlife/galleria-bar)
[/caesars-palace/things-to-do/shopping](https://www.caesars.com/caesars-palace/things-to-do/shopping)
[/caesars-palace/things-to-do/qua](https://www.caesars.com/caesars-palace/things-to-do/qua)
[/caesars-palace/things-to-do/hairdreams-salon](https://www.caesars.com/caesars-palace/things-to-do/hairdreams-salon)
[/caesars-palace/things-to-do/weddings](https://www.caesars.com/caesars-palace/things-to-do/weddings)
[/caesars-palace/things-to-do/weddings/inquiry](https://www.caesars.com/caesars-palace/things-to-do/weddings/inquiry)
[/caesars-palace/things-to-do/weddings/spa-and-salon-services](https://www.caesars.com/caesars-palace/things-to-do/weddings/spa-and-salon-services)
[/caesars-palace/things-to-do/basketball](https://www.caesars.com/caesars-palace/things-to-do/basketball)
[/caesars-palace/things-to-do/hoopsredirect](https://www.caesars.com/caesars-palace/things-to-do/hoopsredirect)
[/caesars-palace/things-to-do/caesars-experiences](https://www.caesars.com/caesars-palace/things-to-do/caesars-experiences)
[/caesars-palace/things-to-do/football](https://www.caesars.com/caesars-palace/things-to-do/football)

**Comment by tmathern** [comment]
Need to check is [/caesars-palace/things-to-do/basketball](https://www.caesars.com/caesars-palace/things-to-do/basketball) and
[/caesars-palace/things-to-do/hoopsredirect](https://www.caesars.com/caesars-palace/things-to-do/hoopsredirect) are still current and should be migrated too.
