### ISSUE TITLE
Block:  Card Slider

### ISSUE THREAD

**Issue by chrismborland** [hlxsites/caesars#38]
**Desktop**

<img width="1452" alt="card-slider-desktop" src="https://user-images.githubusercontent.com/3279046/222236188-36a2af8d-95d0-4b2d-bfff-c5a962f12704.png">

**Tablet**

<img width="806" alt="card-slider-tablet" src="https://user-images.githubusercontent.com/3279046/222236184-ded87a7e-adf8-4976-9da8-1f871ec92953.png">

**Mobile**

<img width="603" alt="card-slider-mobile" src="https://user-images.githubusercontent.com/3279046/222236183-7d84fc0b-2ff4-4a6d-8e14-7e7802c29b37.png">

**Comment by tmathern** [comment]
Note that I think that in phase 2, instead of tabs on mobile we should use the card slider.

**Comment by tmathern** [comment]
Added `Phase 1` label, since it's needed for mobile experience in phase 1.
