### ISSUE TITLE
Block:FAQ

### ISSUE THREAD

**Issue by jfait** [hlxsites/caesars#45]
Seen on https://www.caesars.com/caesars-palace/things-to-do/garden-of-the-gods-pool-oasis

![image](https://user-images.githubusercontent.com/1164937/222527652-2370c192-5d26-44ef-9fb3-41c93a8a7c98.png)

**Comment by jfait** [comment]
@arumsey should i use columns block for FAQ or worth having a distinct block ?

**Comment by tmathern** [comment]
Added `Phase One` label, since it's needed for phase one.
