### ISSUE TITLE
Columns with offset and bg image

### ISSUE THREAD

**Issue by jfait** [hlxsites/caesars#46]
Used in a few pages including https://www.caesars.com/caesars-palace/restaurants

![image](https://user-images.githubusercontent.com/1164937/222530617-19f5c894-a433-4872-b0d2-29dbf1e75d09.png)

**Comment by tmathern** [comment]
This could become its own block _or_ a variation of https://github.com/hlxsites/caesars/issues/14.

**Comment by jfait** [comment]
yep, created this after related conversation in slack

**Comment by tmathern** [comment]
I added the `Phase One` label, since we need it to lift-and-shift the site, no matter if it becomes a variation or its own block.

**Comment by tmathern** [comment]
<img width="1085" alt="Screenshot 2023-03-16 at 9 22 43 AM" src="https://user-images.githubusercontent.com/60901087/225686080-62953335-4ccb-4b69-8f12-8edb9265162b.png">
