### ISSUE TITLE
Stats variation: Amenities

### ISSUE THREAD

**Issue by tmathern** [hlxsites/caesars#74]
<img width="1007" alt="Screenshot 2023-03-15 at 2 09 36 PM" src="https://user-images.githubusercontent.com/60901087/225470028-55b72b82-c66b-4639-9b55-b72d86f7c78e.png">

**Comment by chrismborland** [comment]
At the smallest viewport (< 480px) the tiles should be a single column,

<img width="575" alt="Screenshot 2023-03-21 at 1 36 13 PM" src="https://user-images.githubusercontent.com/3279046/226694577-5dbac22d-0868-4f6d-8660-d61b97eca76e.png">
