### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/caesars#9]
Variation 1: Menu
![Accordian-Menu](https://user-images.githubusercontent.com/7074782/220497520-c7e5334a-cf91-4309-836a-77bc0362ced2.png)

**Comment by amol-anand** [comment]
These can/should be separate blocks since the CSS is completely different for the interactions with the accordian.

**Comment by chrismborland** [comment]
Agreed that these should likely be separate blocks.  We should also consider moving the "Play" portion of the first experience into a separate block - possibly another CTA type or section header.  This is used in several instances.

Let me know if you'd like me to create another issue for this.

<img width="1203" alt="play-cta" src="https://user-images.githubusercontent.com/3279046/220704002-23073e9b-c262-4f45-a44c-00b11b08dba3.png">

<img width="1179" alt="deals-cta" src="https://user-images.githubusercontent.com/3279046/220704020-69538f55-4428-44db-ab7d-2ae1c8552926.png">

<img width="1228" alt="room-cta" src="https://user-images.githubusercontent.com/3279046/220704033-88ff0a11-c766-4c97-a179-61b5677cc4b9.png">

**Comment by amol-anand** [comment]
Agree.. the text on top could just be basic column blocks too. I think it should be a variation of one of the existing column block variations.

**Comment by amol-anand** [comment]
Not sure it won't impact LHS. I would bet it does. But if it doesn't then it is fair game.

**Comment by arumsey** [comment]
Play, Deals, Rooms can all use base `columns` block

<img width="649" alt="image" src="https://user-images.githubusercontent.com/1004204/222253072-36b7ef3c-d0cc-4e4b-bd23-8c1a8b97a2e3.png">

**Comment by tmathern** [comment]
I'd see "vertical hero accordions" (vertical with images) and "horizontal accordions" (horizontal, list-type, no image) here.

**Comment by jfait** [comment]
splitting FAQ out into its own block/issue

**Comment by tmathern** [comment]
As seen in https://www.caesars.com/caesars-palace/casino

**Comment by tmathern** [comment]
On mobile:
<img width="466" alt="Screenshot 2023-03-13 at 1 35 11 PM" src="https://user-images.githubusercontent.com/60901087/224826203-192293cd-dc41-4aeb-a631-6a3a2bce46b1.png">
